export enum GeneralMessageKeyEnum {
  FOREIGN_KEY_CONSTRAINT_VIOLATION = "FOREIGN_KEY_CONSTRAINT_VIOLATION",
  UNIQUE_KEY_CONSTRAINT_VIOLATION = "UNIQUE_KEY_CONSTRAINT_VIOLATION",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  FORBIDDEN = "FORBIDDEN",
  CREDENTIALS_ERROR_VIOLATION = "CREDENTIALS_ERROR_VIOLATION",
  UNAUTHORIZED = "UNAUTHORIZED",
}
