export enum ConfigurationEnum {
  SERVER_PORT = "SERVER_PORT",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSWORD = "DB_PASSWORD",
  DB_DATABASE = "DB_DATABASE",
  DB_POOL_SIZE = "DB_POOL_SIZE",
  CORS_ORIGIN = "CORS_ORIGIN",
  DEV_ENV = "dev",
  LOG_SEVERITIES = "LOG_SEVERITIES",
  JWT_SECRET = "JWT_SECRET",
  ADMINS = "ADMINS",
}
